-- ATTENTION — CE FICHIER N'EST PAS UNE MIGRATION.
--
-- Privileges du socle, releves en lecture seule sur PRODUCTION le 2026-09-05.
-- A executer apres 6-rls-policies.sql sur un environnement NEUF uniquement.
--
-- Les privileges comptent autant que les policies sur ce projet : plusieurs
-- lots de securite (2026-09-01, 2026-09-06 a 2026-09-08) ne consistent qu'en
-- REVOKE. Un socle qui reconstruirait les tables sans les droits produirait un
-- environnement ouvert par defaut, c'est-a-dire l'inverse de l'etat voulu.
--
-- Genere automatiquement. Ne pas modifier a la main : regenerer.

-- Fermeture prealable : on part de rien, puis on n'accorde que le releve.
revoke all on all tables in schema public from anon, authenticated, service_role;
revoke all on all functions in schema public from public, anon, authenticated, service_role;

-- Tables
grant REFERENCES, TRIGGER, TRUNCATE on public.actions_ia to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.actions_ia to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.actions_ia to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on public.clients to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.clients to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.clients to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_jetons to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_jetons to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_jetons to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_rappels_file to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_rappels_file to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.confirmations_rappels_file to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on public.demandes to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.demandes to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.demandes to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.devis to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.devis to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.devis to service_role;
grant DELETE, INSERT, SELECT, UPDATE on public.devis_lignes to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.email_connections to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.email_connections to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.email_connections to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.erreurs_automatisation to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.erreurs_automatisation to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.erreurs_automatisation to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.factures to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.factures to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on public.factures to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.garages to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.garages to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.garages to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.garages_secrets to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.garages_secrets to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on public.garages_secrets to service_role;
grant SELECT on public.horaires_garage to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inspections to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_historique to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE on public.inspections_historique to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_historique to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_jetons to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_jetons to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_jetons to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_photos to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inspections_photos to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_photos to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_points to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE on public.inspections_points to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.inspections_points to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.liste_attente to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.liste_attente to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.liste_attente to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.mecaniciens to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.mecaniciens to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.mecaniciens to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_atelier to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_atelier to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.notifications_atelier to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_devis to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_devis to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.notifications_devis to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_factures to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_factures to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.notifications_factures to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_proposition to anon;
grant REFERENCES, TRIGGER, TRUNCATE on public.notifications_proposition to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.notifications_proposition to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.opportunites_actions to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE on public.opportunites_actions to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.opportunites_actions to service_role;
grant INSERT, SELECT, UPDATE on public.ordres_reparation to authenticated;
grant SELECT on public.ordres_reparation_historique to authenticated;
grant DELETE, INSERT, SELECT, UPDATE on public.ordres_reparation_lignes to authenticated;
grant SELECT on public.prestations to anon;
grant DELETE, INSERT, SELECT, UPDATE on public.prestations to authenticated;
grant DELETE, INSERT, SELECT, UPDATE on public.prestations to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.propositions_rdv to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.propositions_rdv to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.propositions_rdv to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.rappels_manques to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.rappels_manques to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.rappels_manques to service_role;
grant INSERT, SELECT on public.rendez_vous to anon;
grant DELETE, INSERT, SELECT, UPDATE on public.rendez_vous to authenticated;
grant DELETE, INSERT, SELECT, UPDATE on public.rendez_vous to service_role;
grant INSERT, SELECT, UPDATE on public.revenue_recovery_brouillons to authenticated;
grant SELECT on public.revenue_recovery_evenements to authenticated;
grant SELECT on public.revenue_recovery_garages_autorises to authenticated;
grant SELECT on public.revenue_recovery_permissions to authenticated;
grant SELECT on public.revenue_recovery_tentatives to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.travaux_differes to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.travaux_differes to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.travaux_differes to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on public.travaux_differes_historique to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE on public.travaux_differes_historique to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on public.travaux_differes_historique to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on public.vehicules to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vehicules to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vehicules to service_role;

-- Fonctions
grant execute on function public.assigner_numero_facture() to anon;
grant execute on function public.assigner_numero_facture() to authenticated;
grant execute on function public.assigner_numero_facture() to service_role;
grant execute on function public.avancer_etape_atelier_par_jeton(p_token text, p_nouveau_statut text) to anon;
grant execute on function public.avancer_etape_atelier_par_jeton(p_token text, p_nouveau_statut text) to authenticated;
grant execute on function public.creer_jeton_atelier(p_rdv_id uuid) to authenticated;
grant execute on function public.creer_jeton_confirmation(p_rdv_id uuid) to anon;
grant execute on function public.creer_jeton_confirmation(p_rdv_id uuid) to authenticated;
grant execute on function public.creer_jeton_confirmation(p_rdv_id uuid) to service_role;
grant execute on function public.creer_jeton_devis(p_devis_id uuid) to authenticated;
grant execute on function public.creer_jeton_facture(p_facture_id uuid) to authenticated;
grant execute on function public.creer_jeton_inspection(p_inspection_id uuid) to anon;
grant execute on function public.creer_jeton_inspection(p_inspection_id uuid) to authenticated;
grant execute on function public.creer_jeton_inspection(p_inspection_id uuid) to service_role;
grant execute on function public.current_garage_id() to anon;
grant execute on function public.current_garage_id() to authenticated;
grant execute on function public.current_garage_id() to service_role;
grant execute on function public.devis_statut_modifiable(p_statut text) to authenticated;
grant execute on function public.finaliser_inspection(p_inspection_id uuid) to anon;
grant execute on function public.finaliser_inspection(p_inspection_id uuid) to authenticated;
grant execute on function public.finaliser_inspection(p_inspection_id uuid) to service_role;
grant execute on function public.inspections_bloquer_contenu_si_verrouillee() to anon;
grant execute on function public.inspections_bloquer_contenu_si_verrouillee() to authenticated;
grant execute on function public.inspections_bloquer_contenu_si_verrouillee() to service_role;
grant execute on function public.inspections_log_historique() to anon;
grant execute on function public.inspections_log_historique() to authenticated;
grant execute on function public.inspections_log_historique() to service_role;
grant execute on function public.inspections_photos_bloquer_si_verrouillee() to anon;
grant execute on function public.inspections_photos_bloquer_si_verrouillee() to authenticated;
grant execute on function public.inspections_photos_bloquer_si_verrouillee() to service_role;
grant execute on function public.inspections_points_bloquer_si_verrouillee() to anon;
grant execute on function public.inspections_points_bloquer_si_verrouillee() to authenticated;
grant execute on function public.inspections_points_bloquer_si_verrouillee() to service_role;
grant execute on function public.inspections_set_updated_at() to anon;
grant execute on function public.inspections_set_updated_at() to authenticated;
grant execute on function public.inspections_set_updated_at() to service_role;
grant execute on function public.lire_atelier_par_jeton(p_token text) to anon;
grant execute on function public.lire_atelier_par_jeton(p_token text) to authenticated;
grant execute on function public.lire_confirmation_par_jeton(p_token text) to anon;
grant execute on function public.lire_confirmation_par_jeton(p_token text) to authenticated;
grant execute on function public.lire_confirmation_par_jeton(p_token text) to service_role;
grant execute on function public.lire_confirmation_rdv_public(p_rdv_id uuid) to anon;
grant execute on function public.lire_confirmation_rdv_public(p_rdv_id uuid) to authenticated;
grant execute on function public.lire_confirmation_rdv_public(p_rdv_id uuid) to service_role;
grant execute on function public.lire_devis_par_jeton(p_token text) to anon;
grant execute on function public.lire_devis_par_jeton(p_token text) to authenticated;
grant execute on function public.lire_facture_par_jeton(p_token text) to anon;
grant execute on function public.lire_facture_par_jeton(p_token text) to authenticated;
grant execute on function public.lire_inspection_par_jeton(p_token text) to anon;
grant execute on function public.lire_inspection_par_jeton(p_token text) to authenticated;
grant execute on function public.lire_inspection_par_jeton(p_token text) to service_role;
grant execute on function public.notification_abandonner(p_id uuid) to authenticated;
grant execute on function public.notification_reessayer(p_id uuid) to authenticated;
grant execute on function public.notifications_a_verifier() to authenticated;
grant execute on function public.notifications_vehicule_pret_en_attente() to service_role;
grant execute on function public.notifier_devis_maj() to anon;
grant execute on function public.notifier_devis_maj() to authenticated;
grant execute on function public.notifier_devis_maj() to service_role;
grant execute on function public.notifier_facture_payee() to anon;
grant execute on function public.notifier_facture_payee() to authenticated;
grant execute on function public.notifier_facture_payee() to service_role;
grant execute on function public.notifier_nouveau_devis() to anon;
grant execute on function public.notifier_nouveau_devis() to authenticated;
grant execute on function public.notifier_nouveau_devis() to service_role;
grant execute on function public.notifier_nouvelle_facture() to anon;
grant execute on function public.notifier_nouvelle_facture() to authenticated;
grant execute on function public.notifier_nouvelle_facture() to service_role;
grant execute on function public.notifier_proposition_maj() to anon;
grant execute on function public.notifier_proposition_maj() to authenticated;
grant execute on function public.notifier_proposition_maj() to service_role;
grant execute on function public.notifier_vehicule_pret() to anon;
grant execute on function public.notifier_vehicule_pret() to authenticated;
grant execute on function public.notifier_vehicule_pret() to service_role;
grant execute on function public.opportunites_actions_forcer_identite() to anon;
grant execute on function public.opportunites_actions_forcer_identite() to authenticated;
grant execute on function public.opportunites_actions_forcer_identite() to service_role;
grant execute on function public.preparer_rappels_confirmation() to anon;
grant execute on function public.preparer_rappels_confirmation() to authenticated;
grant execute on function public.preparer_rappels_confirmation() to service_role;
grant execute on function public.reouvrir_inspection(p_inspection_id uuid, p_motif text) to anon;
grant execute on function public.reouvrir_inspection(p_inspection_id uuid, p_motif text) to authenticated;
grant execute on function public.reouvrir_inspection(p_inspection_id uuid, p_motif text) to service_role;
grant execute on function public.repondre_confirmation_par_jeton(p_token text, p_reponse text) to anon;
grant execute on function public.repondre_confirmation_par_jeton(p_token text, p_reponse text) to authenticated;
grant execute on function public.repondre_confirmation_par_jeton(p_token text, p_reponse text) to service_role;
grant execute on function public.repondre_confirmation_rdv_public(p_rdv_id uuid, p_reponse text) to anon;
grant execute on function public.repondre_confirmation_rdv_public(p_rdv_id uuid, p_reponse text) to authenticated;
grant execute on function public.repondre_confirmation_rdv_public(p_rdv_id uuid, p_reponse text) to service_role;
grant execute on function public.repondre_devis_par_jeton(p_token text, p_reponse text) to anon;
grant execute on function public.repondre_devis_par_jeton(p_token text, p_reponse text) to authenticated;
grant execute on function public.repondre_point_inspection_par_jeton(p_token text, p_point_id uuid, p_decision text) to anon;
grant execute on function public.repondre_point_inspection_par_jeton(p_token text, p_point_id uuid, p_decision text) to authenticated;
grant execute on function public.repondre_point_inspection_par_jeton(p_token text, p_point_id uuid, p_decision text) to service_role;
grant execute on function public.revenue_recovery_brouillons_identite_insert() to anon;
grant execute on function public.revenue_recovery_brouillons_identite_insert() to authenticated;
grant execute on function public.revenue_recovery_brouillons_identite_insert() to service_role;
grant execute on function public.revenue_recovery_brouillons_verrouiller() to anon;
grant execute on function public.revenue_recovery_brouillons_verrouiller() to authenticated;
grant execute on function public.revenue_recovery_brouillons_verrouiller() to service_role;
grant execute on function public.revenue_recovery_enregistrer_permission(p_garage_id uuid, p_client_id uuid, p_canal text, p_statut text, p_origine text, p_travail_differe_id uuid, p_base_eligibilite text, p_preuve_reference text, p_motif text) to authenticated;
grant execute on function public.revenue_recovery_evenements_forcer_identite() to anon;
grant execute on function public.revenue_recovery_evenements_forcer_identite() to authenticated;
grant execute on function public.revenue_recovery_evenements_forcer_identite() to service_role;
grant execute on function public.revenue_recovery_garages_autorises_set_updated_at() to anon;
grant execute on function public.revenue_recovery_garages_autorises_set_updated_at() to authenticated;
grant execute on function public.revenue_recovery_garages_autorises_set_updated_at() to service_role;
grant execute on function public.revenue_recovery_permissions_forcer_identite() to anon;
grant execute on function public.revenue_recovery_permissions_forcer_identite() to authenticated;
grant execute on function public.revenue_recovery_permissions_forcer_identite() to service_role;
grant execute on function public.revenue_recovery_tentatives_forcer_identite() to anon;
grant execute on function public.revenue_recovery_tentatives_forcer_identite() to authenticated;
grant execute on function public.revenue_recovery_tentatives_forcer_identite() to service_role;
grant execute on function public.revoquer_jeton_atelier(p_rdv_id uuid) to authenticated;
grant execute on function public.revoquer_jeton_devis(p_devis_id uuid) to authenticated;
grant execute on function public.revoquer_jeton_facture(p_facture_id uuid) to authenticated;
grant execute on function public.revoquer_jeton_inspection(p_inspection_id uuid) to anon;
grant execute on function public.revoquer_jeton_inspection(p_inspection_id uuid) to authenticated;
grant execute on function public.revoquer_jeton_inspection(p_inspection_id uuid) to service_role;
grant execute on function public.rls_auto_enable() to anon;
grant execute on function public.rls_auto_enable() to authenticated;
grant execute on function public.rls_auto_enable() to service_role;
grant execute on function public.set_stripe_secret_key(p_key text) to anon;
grant execute on function public.set_stripe_secret_key(p_key text) to authenticated;
grant execute on function public.set_stripe_secret_key(p_key text) to service_role;
grant execute on function public.stripe_configure_pour_mon_garage() to anon;
grant execute on function public.stripe_configure_pour_mon_garage() to authenticated;
grant execute on function public.stripe_configure_pour_mon_garage() to service_role;
grant execute on function public.travaux_differes_log_historique() to anon;
grant execute on function public.travaux_differes_log_historique() to authenticated;
grant execute on function public.travaux_differes_log_historique() to service_role;
grant execute on function public.travaux_differes_set_updated_at() to anon;
grant execute on function public.travaux_differes_set_updated_at() to authenticated;
grant execute on function public.travaux_differes_set_updated_at() to service_role;
